### ISSUE TITLE
Code samples for "UNDERSTANDING THE LOW-RANK UPDATES" chapter (chapter 7).

### ISSUE THREAD

**Issue by agoncharenko1992** [microsoft/LoRA#100]
Hello there! Thanks for your great work!

Could you please provide some code for generating results for chapter 7 (UNDERSTANDING THE LOW-RANK UPDATES)? I mean all stuff for calculating Grassman distance and so on.

Thanks!

**Comment by edwardjhu** [comment]
It was in a Jupyter notebook on my MSFT github, which I unfortunately don't have access to anymore :(

Sorry about that! It should be relatively simple to code up though.

**Comment by agoncharenko1992** [comment]
Ok, thanks!
