### ISSUE TITLE
Error in MergedLinear

### ISSUE THREAD

**Issue by Baijiong-Lin** [microsoft/LoRA#103]
![image](https://github.com/microsoft/LoRA/assets/53974477/7bd94aa3-1e4f-4a5a-8f7a-8178c840e90d)

It seems ``fan_in_fan_out`` must be ``True`` in ``MergedLinear``.

**Comment by edwardjhu** [comment]
Thanks for catching this! I fixed it here: https://github.com/microsoft/LoRA/tree/bugfix_MergedLinear

Could you give it a try and see if this resolves the issue for you?

**Comment by maohaotiancs** [comment]
I have encountered a similar problem.
When I training on gpu, error happened.
![截屏2023-07-26 17 03 55](https://github.com/microsoft/LoRA/assets/69193269/9bc15932-2527-490a-8b28-c6dd0275852d)
![截屏2023-07-26 17 04 06](https://github.com/microsoft/LoRA/assets/69193269/9cea2504-a178-4487-9c33-4356c01a950f)

**Comment by Baijiong-Lin** [comment]
> Thanks for catching this! I fixed it here: https://github.com/microsoft/LoRA/tree/bugfix_MergedLinear
> 
> Could you give it a try and see if this resolves the issue for you?

@edwardjhu I got the same error as @maohaotiancs. 

``model.eval()`` can be run normally in both ``fan_in_fan_out=True`` and ``fan_in_fan_out=False`` cases but the forward process has an error when ``model.train()``.

![image](https://github.com/microsoft/LoRA/assets/53974477/72d40a54-b1f2-4341-bce4-1bcaf318030c)

**Comment by Baijiong-Lin** [comment]
@edwardjhu @maohaotiancs I have fixed this bug  (#105).

**Comment by edwardjhu** [comment]
Looks good to me! Thanks @Baijiong-Lin 

If this is now resolved, feel free to close the issue and I'll merge the patch with main
