### ISSUE TITLE
The content on pypi does not seem to be updated

### ISSUE THREAD

**Issue by MikuAndRabbit** [microsoft/LoRA#117]
Hello, dear developer. I noticed that the content of loralib on pypi seems to be stuck at version 0.1.1. There is a serious bug in this version where calling `model.eval()` mentioned in #34 doesn't work. This problem has been fixed in the repository ([code here](https://github.com/microsoft/LoRA/blob/7036ee01b45dd4d4eb708941ffe1b5b414a013d5/loralib/layers.py#L136-L141)), but since the version on pypi has not been updated, this may confuse some developers.

Please developers have time to update the content on pypi (I don't know how to do this part), thank you very much.

**Comment by THU-syh** [comment]
Agree it！

**Comment by edwardjhu** [comment]
Thanks for flagging this! I just updated pypi.

**Comment by MikuAndRabbit** [comment]
> Thanks for flagging this! I just updated pypi.

Thank you.
