### ISSUE TITLE
AttributeError: 'lora.Conv2d' object has no attribute 'weight'

### ISSUE THREAD

**Issue by bjzhb666** [microsoft/LoRA#134]
Thanks for your great work!

When I use `loralib-0.1.2`, I get this error. 
In `nn.Conv2d`, it has the attribute 'weight'.
I think it is better to add `weight` attribute to our `lora.Conv2d`.

It is interesting that in version `loralib-0.1.1`, `lora.Conv2d` has this attribute, but in the latest version, my code gives me this bug.
```[tasklist]
### Tasks
```

**Comment by RasmusD** [comment]
It's because of this PR: https://github.com/microsoft/LoRA/pull/63

**Comment by edwardjhu** [comment]
Good catch. It's now `self.conv.weight`.

**Comment by bjzhb666** [comment]
Thanks for your replies!
