### ISSUE TITLE
LoRA/loralib/layers.py line 71 nn.Linear.eval() using.

### ISSUE THREAD

**Issue by ericshijian** [microsoft/LoRA#21]
Hi,

For LoRA/loralib/layers.py line 71, should we use nn.Embedding.eval() instead of nn.Linear.eval() here.
![image](https://user-images.githubusercontent.com/6739216/169230585-1f87ab4d-cf9b-4fc9-8394-8d95fbbe649e.png)

**Comment by edwardjhu** [comment]
Thanks! Corrected.
