### ISSUE TITLE
What does `lora_moe` mean?

### ISSUE THREAD

**Issue by luofuli** [microsoft/LoRA#4]
Good job! I extremely like LoRA. After a shot glimpse of the code, I find some config is related to `lora_moe` in `model.py.` But I did not see any arguments related to `lora_moe` in `gpt2_ft.py`. Can you give more introductions about `lora_moe`? Is it designed for models which are trained with moe? Or is it just a deprecated feature of LoRA？

**Comment by edwardjhu** [comment]
Hi luofuli,

Thanks for your interest in our work! We unfortunately forgot to remove some experimental features in our last release (yes, we were playing with MoE!). We just cleaned up our repo and included a new package `loralib` which makes applying LoRA much more straightforward than before.

**Comment by abodacs** [comment]
@edwardjhu Thanks for your work.

Did you have a positive result when you experimenting LoRA with MoE?

**Comment by edwardjhu** [comment]
> @edwardjhu Thanks for your work.
> 
> Did you have a positive result when you experimenting LoRA with MoE?

Hi Abdullah, we don't have anything to share wrt MoE at the moment. Please stay tuned!

**Comment by rachitgarg91** [comment]
Hi Edward, Did we see any positive results with LoRA finetuning on MoE models?
