### ISSUE TITLE
[BUG] model.eval() does not merge weights

### ISSUE THREAD

**Issue by vince62s** [microsoft/LoRA#61]
the reason is:
model.eval() does not call recursively modules.eval() but modules.train(false)

so the lora.eval() is never called unless you call them unitary.

cf: https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L2306

**Comment by edwardjhu** [comment]
Thanks for flagging this! This was pointed out and fixed late year, but I forgot to merge it to main. It should be merged now. Let me know if it doesn't work for you!

**Comment by vince62s** [comment]
I did the same changes.
work very fine. FYI: https://forum.opennmt.net/t/finetuning-a-llama-7b-model-and-reproduce-vicuna-alpaca/5272

**Comment by vince62s** [comment]
actually there is a missing transpose here: https://github.com/microsoft/LoRA/blob/main/loralib/layers.py#L74

**Comment by edwardjhu** [comment]
You are right. Thanks Vincent!
