### ISSUE TITLE
Conv2D and groups > 1

### ISSUE THREAD

**Issue by bbbxyz** [microsoft/LoRA#67]
Conv2D seems broken with groups > 1, for example with `Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=256, r=8)` and an input of size `input of shape torch.Size([32, 256, 64, 64])` I get the following error:
```
  File "/home/miniconda3/envs/pytorch2/lib/python3.10/site-packages/loralib/layers.py", line 319, in forward
    self.weight + (self.lora_B @ self.lora_A).view(self.weight.shape) * self.scaling,
RuntimeError: shape '[256, 1, 3, 3]' is invalid for input of size 589824
```

I believe the first dimension should be calculated as `out_channels//self.groups*kernel_size` here: https://github.com/microsoft/LoRA/blob/main/loralib/layers.py#L280

Here's a full example:
```
import torch
import loralib as lora

conv = lora.Conv2d(256, 256, 3, groups = 1, r=8)
grouped_conv = lora.Conv2d(256, 256, 3, groups = 2, r=8)
input_tensor = torch.randn((8, 256, 32, 32))

conv(input_tensor)
grouped_conv(input_tensor)
```

**Comment by ExponentialML** [comment]
Since it seems to be related, there's a possible issue when it comes to scaling Conv2d.
It seems that when creating new parameters, we have:

```python
self.lora_A = nn.Parameter(
                self.weight.new_zeros((r*kernel_size, in_channels*kernel_size))
            )
self.lora_B = nn.Parameter(
    self.weight.new_zeros((out_channels*kernel_size, r*kernel_size))
```

The kernel size here is multiplied by the rank. We then scale this by `self.scale = alpha / r`.
I believe the appropriate solution should be something like:

```python
self.scale = alpha / (r // kernel_size)
```

**Comment by edwardjhu** [comment]
Thanks everyone! This is indeed a bug.

Because the LoRA module in this case doesn't have a convolution structure, I don't see a reason to prefer one fix over another.

It's fixed now. https://github.com/microsoft/LoRA/commit/375704a4f7e376f8f1c4b43e2fd524859dac6a59

**Comment by bbbxyz** [comment]
Thanks @edwardjhu !

**Comment by luchaoqi** [comment]
Hi @edwardjhu , I have a similar question about the conv2d implementation [here](https://github.com/microsoft/LoRA/blob/3f5c193f431c8a09448f0184f6f883ad393f22d0/loralib/layers.py#L284C21-L284C21):
```
self.conv.weight.data += (self.lora_B @ self.lora_A).view(self.conv.weight.shape) * self.scaling
```
Assuming `group = 1`, the output of `self.lora_B @ self.lora_A` should be in the shape of `out_c•k * in_c•k` which is a 2D matrix. Then it is viewed in the shape of `self.conv.weight.shape = out_c, in_c, k, k`.
If I understand correctly, the order of elements should rather be aligned like:
```
self.conv.weight.data += (self.lora_B @ self.lora_A).view(self.conv2d_layer.out_channels, self.conv2d_layer.kernel_size, self.conv2d_layer.in_channels, self.conv2d_layer.kernel_size).permute(0, 2, 1, 3)* self.scaling
```
lmk if I misunderstand something, thanks for your time!
