### ISSUE TITLE
Inference benefits

### ISSUE THREAD

**Issue by austinmw** [microsoft/LoRA#68]
Hi, I'm curious if LoRA can provide any benefits in reducing model size or latency during inference? Could this or related techniques help make deploying LLMs to edge devices more feasible?

My current understanding is that this mostly benefits training rather than inference, because the model is reconstructed to full size after the low-rank adaptation. 

It also seems to provide benefit when it's desired to have multiple models for different tasks. However if the desire is to have a single LLM deployed for inference more efficiently on an edge device, are there any benefits to be had in this case?

I appreciate any clarification you can provide, thanks!

**Comment by edwardjhu** [comment]
Thanks for the question, Austin.

In terms of inference, LoRA doesn't make a pretrained model run any faster. When used appropriately, it provides a way to customize that model flexibly without making it slower at inference time. If the goal is to make a single LLM run faster on an edge device, the relevant areas to look into might be model compression, distillation, and quantization.

Hope this helps!

**Comment by austinmw** [comment]
Thanks, really appreciate your response!
