### ISSUE TITLE
Questions about Frobenius norm (Table 7)

### ISSUE THREAD

**Issue by zhiyuanyou** [microsoft/LoRA#70]
Hi~

Thanks for your excellent work.

I have a question about the Table 7, where you calculate Frobenius norm. In my view, setting the rank as 4 or 64 only affects $\Delta W_q$, and does not affect $W_q$. The figures at (a) and (b) in the following table are only relevant to $W_q$, since $U, V, W_q$ all come from $W_q$. Therefore, the figures at (a) and (b) **_should be the same_**. I could not figure out why they are different. 

<img width="680" alt="image" src="https://github.com/microsoft/LoRA/assets/42168004/088b2a00-fef9-4b99-a2e9-a07d4c185b90">

Is there anything I understood wrong?

**Comment by edwardjhu** [comment]
Thanks for the question, Zhiyuan.

U and V are the top **r** singular vectors. That's why they are different even though W_q is the same.

**Comment by zhiyuanyou** [comment]
Thanks. It makes perfect sense to me now.

**Comment by zhiyuanyou** [comment]
Hi~

Thanks for your help. I read through Sec. 7.3 in detail, and I finally figure out why you use the singular-vector matrix and Frobenius norm. Since I would like to use similar analysis method, I have another little detailed question. 

You use $||U^T W_q V^T||$ to measure the scale of $W_q$ projected to the space spanned by $U,V$, where $U,V$ are the left, right singular-vector matrix of $\Delta_W$ or $W_q$. 

Here, in SVD decomposition, there are 2 forms of writing: (a) $A = U \sum V$, (b) $A = U \sum V^T$. Since you use $||U^T W_q V^T||$ in the paper ($V$ has a superscript $T$), so I think you should use (a), which means you directly use the right matrix as $V$ **_without transposition_**. 

Is it right?

Thanks again.

**Comment by ZeguanXiao** [comment]
@zhiyuanyou Same question here. Are you figured out?
