### ISSUE TITLE
Initialization of class Embedding

### ISSUE THREAD

**Issue by akmtn** [microsoft/LoRA#76]
Is this correct? or Should lora_B be zero?
https://github.com/microsoft/LoRA/blob/375704a4f7e376f8f1c4b43e2fd524859dac6a59/loralib/layers.py#L58-L60

**Comment by edwardjhu** [comment]
Thanks for pointing this out. This shouldn't make a difference in practice as long as one of them is zero and another non-zero. Modifying it might render previous runs unreproducible.
