### ISSUE TITLE
A question about the implementation of LoRA in the GLUE Benchmark

### ISSUE THREAD

**Issue by song-wx** [microsoft/LoRA#77]
In the scripts of the implementaion of LoRA in GLUE Benchmark, for instance in "roberta_base_mrpc.sh" and "roberta_base_rte.sh", you include the args "--lora_path roberta_base_lora_mnli.bin", whose final result is pretty high. But without initializing LoRA layers with "roberta_base_lora_mnli.bin", the result goes down. And I wonder why we need to initialize LoRA layer with it.

**Comment by Zeju1997** [comment]
Hi, did you find out why LoRA need to initialize the LoRA layers with roberta_base_lora_mnli.bin? Thank you very much.
Best,

**Comment by Zeju1997** [comment]
Hi, did you find out why LoRA need to initialize the LoRA layers with roberta_base_lora_mnli.bin? Thank you very much.
Best,

**Comment by song-wx** [comment]
> Hi, did you find out why LoRA need to initialize the LoRA layers with roberta_base_lora_mnli.bin? Thank you very much. Best,
Yes, this is because the experiments in the roberta paper suggest that initializing with the mnli module produces better results, and lora set up their experiments with this( they have explained in section 5.2 and D.1), and lora also give results without mnli initialization (not marked by the \dag in the figure), and their results do not differ much from the ones I reproduced. 
Hope this might be useful to you.

**Comment by song-wx** [comment]
> Hi, did you find out why LoRA need to initialize the LoRA layers with roberta_base_lora_mnli.bin? Thank you very much. Best,


Yes, this is because the experiments in the roberta paper suggest that initializing with the mnli module produces better results, and lora set up their experiments with this( they have explained in section 5.2 and D.1), and lora also give results without mnli initialization (not marked by the \dag in the figure), and their results do not differ much from the ones I reproduced.
Hope this might be useful to you.
