### ISSUE TITLE
MergedLinear bug?

### ISSUE THREAD

**Issue by shipengai** [microsoft/LoRA#92]
Hi, I meet a issue:
after_B = F.conv1d(
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [50, 14, 16, 14]

`result = F.linear(x, T(self.weight), bias=self.bias)
            if self.r > 0:
                after_A = F.linear(self.lora_dropout(x), self.lora_A)
                after_B = F.conv1d(
                    after_A.transpose(-2, -1), 
                    self.lora_B.unsqueeze(-1), 
                    groups=sum(self.enable_lora)
                ).transpose(-2, -1)
                result += self.zero_pad(after_B) * self.scaling`
x.shape is [50, 14, 14, 768]
lora_A.shape is [16, 768]
after_A.shape is ([50, 14, 14, 16])

How to fix it?

**Comment by shipengai** [comment]
I have fix it up.

**Comment by godlin-bd** [comment]
Hey bro, I met the same question as yours, could you please tell me how to fix it?
